image: fedora:rawhide
stages:
  - build
  - test
  - review

variables:
  DEPENDENCIES: glib-devel gtk3-devel libcanberra-devel libdvdread-devel
                libnotify-devel libsecret-devel libpwquality-devel
                libudisks2-devel xz-devel systemd-devel meson gcc
                glibc-devel gettext
  OPTIONS: -Dman=false

flatpak:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: test

  variables:
    BUNDLE: "org.gnome.DiskUtility.flatpak"
    MANIFEST_PATH: "flatpak/org.gnome.DiskUtility.json"
    FLATPAK_MODULE: "gnome-disk-utility"
    DBUS_ID: "org.gnome.DiskUtility"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"

  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} app ${MANIFEST_PATH}
    - flatpak build app meson --prefix=/app ${OPTIONS} _build
    - flatpak build app ninja -C _build install

    - flatpak-builder --finish-only --repo=repo app ${MANIFEST_PATH}
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${DBUS_ID}

  artifacts:
    paths:
      - ${BUNDLE}
      - _build/meson-logs/meson-log.txt
    expire_in: 6 hours

  cache:
    paths:
      - .flatpak-builder/cache

review:
  stage: review
  dependencies:
    - flatpak
  script:
    - echo "Generating flatpak deployment"
  artifacts:
    paths:
      - ${BUNDLE}
    expire_in: 30 days
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://gitlab.gnome.org/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/${BUNDLE}
    on_stop: stop_review

build:
  stage: build
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build $OPTIONS
    - ninja -C _build
    - ninja -C _build install

stop_review:
  stage: review
  script:
    - echo "Stopping flatpak deployment"
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  except:
    variables:
      - $CI_PIPELINE_SOURCE == "schedule"
