[package]
name = "gnome-disk-utilities"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "GPL-2.0-or-later"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = 'gnome-disk-image-mounter'
path = "src/disk-image-mounter/main.rs"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.8", package = "gtk4", features = [
    "v4_12",
    "xml_validation",
] }
log = "0.4.20"
env_logger = "0.11.2"
adw = { package = "libadwaita", version = "0.6", features = ["v1_4"] }
udisks = { package = "udisks-rs", git = "https://github.com/FineFindus/udisks-rs.git", rev = "0024111e552dd5a96dc17c359c1ab91d2b4dc913" }
zbus = "3"

[build-dependencies]
glib-build-tools = "0.19.0"
