[package]
name = "gnome-disk-utilities"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "GPL-2.0-or-later"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = 'gnome-disk-image-mounter'
path = "src/disk-image-mounter/main.rs"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7", package = "gtk4", features = ["v4_8"] }
log = "0.4.20"
env_logger= "0.10.0"
adw = { package = "libadwaita", version = "0.5.2", features = ["v1_3"] }

[build-dependencies]
glib-build-tools = "0.18.0"
